-- Requires in one place
require('plugin')
require('options')
require('colortheme')
require('nvim-tree-config')
require('treesitter-config')
require('harpoon-config')
require('undotree-config')
require('fugitive-config')
require('telescope-config')
require('lsp-zero-config')
require('comment-config')
require('lualine-config')
require('indent_blankline-config')
require('vimtex-config')
require('which-key-config')
-- require('bufferline-config')
-- require('auto-session-config')
