-- Requires in one place
require('plugin')
require('options')
-- require('onenord-config')
-- require('nord-config')
-- require('tokyonight-config')
require('nordic-config')
require('nvim-tree-config')
require('treesitter-config')
require('harpoon-config')
require('undotree-config')
require('fugitive-config')
require('telescope-config')
require('lsp-zero-config')
require('comment-config')
require('lualine-config')
require('indent_blankline-config')
