require("seshu.plugins-setup")
require("seshu.core.colorscheme")
require("seshu.core.keymaps")
require("seshu.core.options")
require("seshu.plugins.comment")
require("seshu.plugins.nvim-tree")
require("seshu.plugins.lualine")
require("seshu.plugins.telescope")
require("seshu.plugins.nvim-cmp")
require("seshu.plugins.lsp.mason")
require("seshu.plugins.lsp.lspsaga")
require("seshu.plugins.lsp.lspconfig")
-- require("josean.plugins.lsp.null-ls")
require("josean.plugins.vimtex")
